apply vscode powershell formatting
ngetchell/PSGitLab pull request #208
Opened 2019-03-16 05:02 UTC by casz

Goes to show the level of inconsistency :smile: 

fixes #207

2019-03-17 02:20 UTC, ngetchell commented
Does the editorconfig VS Code extension provide something that the PowerShell extension doesn't when it comes to formatting? I think I prefer the Format Document function over the installation of another extension. It is language aware and visually appealing. 

I'm not going to accept a PR that requires me to test every file. I didn't invest enough time in automated tests to make sure this whitespace changes won't break anything. I simply don't have the time to do it by hand. 

The commit changing the if elseif elseif..... to a switch would be accepted as a PR.

2019-03-17 02:25 UTC, ngetchell requested changes
Is another vs code extension (above the ps ext) needed to perform this or can it be done within the Format Document functionality inside vs code?

2019-03-17 02:25 UTC, ngetchell commented on PSGitLab/Private/FormatCommits.ps1
> +          6 { $output.Sat = $day.Count }
There should be a default case, even if it only exists to throw an error.

2019-03-17 11:30 UTC, casz commented
@ngetchell `.editorconfig` is used to tell the user and their editor what is expected.

#198 added tabs for instance in a new file, which furthers the inconsistency.

Of course, if the user uses an editor without support for `.editorconfig` it is no good, but then we have CI to check.

2019-03-17 11:47 UTC, casz commented
In the process of adding PSScriptAnalyze with some extra rules to have Appveyor run those :)

Current count is 2225 (Reverted format commit due to merges :wink:)

2019-03-17 15:13 UTC, casz commented
This should fail on appveyor due to linting and the next commit should hopefully fix most of it and then the next commit will fix the rest :smile:

2019-03-17 15:19 UTC, casz commented
@ngetchell what do you think about `alignPropertyValuePairs` rule? The current standard looked like no alignment so that's what I went with. 
Which meant I had to commit `.vscode/settings.json` for that since it is the default.

2019-03-17 20:07 UTC, it-praktyk commented
I like that change!

2021-08-15 23:39 UTC, ngetchell commented
I will update the files as I go with the VS Code formatter but I am not interested in a PR this large to make sweeping changes to the module.

2021-08-15 23:39 UTC, closed without merging